= CLI Reference
:description: The command-line interface (CLI) tools let you manage and monitor your Couchbase Server installation including clusters, servers, vBuckets, and XDCR.
:tools-ver: 7.6.4

[abstract]
{description}

The Couchbase Server installation process installs the command-line tools.
After installation, the location of these tools depends on your platform:

[cols="50,313"]
|===
| Operating System | Directory Locations

| Linux
a| 
* [.path]`/opt/couchbase/bin`
* [.path]`/opt/couchbase/bin/install`
* [.path]`/opt/couchbase/bin/tools`

| Windows
a|
* [.path]`C:\Program Files\couchbase\server\bin`
* [.path]`C:\Program Files\couchbase\server\bin\install`
* [.path]`C:\Program Files\couchbase\server\bin\tools`

| Mac OS X
a| 
* [.path]`/Applications/Couchbase Server.app/Contents/Resources/couchbase-core/bin`
* [.path]`/Applications/Couchbase Server.app/Contents/Resources/couchbase-core/bin/tools`
* [.path]`/Applications/Couchbase Server.app/Contents/Resources/couchbase-core/bin/install`
|===

== Managing Diagnostics

The command-line interface provides commands to start, stop, and report status for log collection.
You can collect diagnostics through the command-line interface by using the xref:cli:cbcli/couchbase-cli.adoc[`couchbase-cli`] or the xref:cbcollect-info-tool.adoc[`cbcollect_info`] tool.

[#server-tools-packages]
== Server Tools Packages

For convenience, Couchbase provides the Server developer tools package and the Server admin tools package.

=== Server Developer Tools Package

The Server developer tools package lets you install the following EE Server utilities on the systems where you have not installed Couchbase Server:

* xref:tools:cbimport.adoc[`cbimport`]
* xref:tools:cbexport.adoc[`cbexport`]
* xref:cli:cbq-tool.adoc[`cbq`]
* xref:backup-restore:cbbackupmgr.adoc[`cbbackupmgr`]


Download the command line tools package for your platform from the following links:

* Linux: https://packages.couchbase.com/releases/{tools-ver}/couchbase-server-dev-tools_{tools-ver}-linux_x86_64.tar.gz[]
* Linux aarch64: https://packages.couchbase.com/releases/{tools-ver}/couchbase-server-dev-tools_{tools-ver}-linux_aarch64.tar.gz[]
* macOS: https://packages.couchbase.com/releases/{tools-ver}/couchbase-server-dev-tools_{tools-ver}-macos_x86_64.zip[]
* macOS arm64: https://packages.couchbase.com/releases/{tools-ver}/couchbase-server-dev-tools_{tools-ver}-macos_arm64.zip[]
* Windows: https://packages.couchbase.com/releases/{tools-ver}/couchbase-server-dev-tools_{tools-ver}-windows_amd64.zip[]

Unzip or untar the packages, and the binaries are ready to run.
For example:

[source,console,subs="attributes+"]
----
wget https://packages.couchbase.com/releases/{tools-ver}/couchbase-server-dev-tools_{tools-ver}-linux_x86_64.tar.gz

tar -xf couchbase-server-dev-tools_{tools-ver}-linux_x86_64.tar.gz
----

Each package also contains a `README` file and a copy of the software license.

NOTE: On Windows, you must have a recent version of the Microsoft Visual {cpp} Redistributable runtime libraries installed.
If you do not have these libraries installed, download them from https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170[Microsoft Visual {cpp} Redistributable latest supported downloads].

=== Server Admin Tools Package

The Server admin tools package lets you install the following Server utilities on the systems where you have not installed Couchbase Server:

* xref:backup-restore:cbbackupmgr.adoc[`cbbackupmgr`]
* https://docs.couchbase.com/sdk-api/couchbase-c-client/md_doc_2cbc.html[`cbc`]
* xref:tools:cbdatarecovery.adoc[`cbdatarecovery`]
* xref:tools:cbexport.adoc[`cbexport`]
* xref:tools:cbimport.adoc[`cbimport`]
* xref:cli:cbq-tool.adoc[`cbq`]
* xref:cli:cbstats-intro.adoc[`cbstats`]
* xref:cli:cbcli/couchbase-cli.adoc[`couchbase-cli`]
* xref:cli:mcstat.adoc[`mcstat`]
* xref:cli:mctimings.adoc[`mctimings`]
* xref:cli:mctestauth.adoc[`mctestauth`]

Download the command line tools package for your platform from the following links:

* Linux: https://packages.couchbase.com/releases/{tools-ver}/couchbase-server-admin-tools_{tools-ver}-linux_x86_64.tar.gz[]
* Linux aarch64: https://packages.couchbase.com/releases/{tools-ver}/couchbase-server-admin-tools_{tools-ver}-linux_aarch64.tar.gz[]
* macOS: https://packages.couchbase.com/releases/{tools-ver}/couchbase-server-admin-tools_{tools-ver}-macos_x86_64.zip[]
* macOS arm64: https://packages.couchbase.com/releases/{tools-ver}/couchbase-server-admin-tools_{tools-ver}-macos_arm64.zip[]
* Windows: https://packages.couchbase.com/releases/{tools-ver}/couchbase-server-admin-tools_{tools-ver}-windows_amd64.zip[]

Unzip or untar the packages, and the binaries are ready to run.
For example:

[source,console,subs="attributes+"]
----
wget https://packages.couchbase.com/releases/{tools-ver}/couchbase-server-admin-tools_{tools-ver}-linux_x86_64.tar.gz

tar -xf couchbase-server-admin-tools_{tools-ver}-linux_x86_64.tar.gz
----

Each package also contains a `README` file and a copy of the software license.

NOTE: On Windows, you must have a recent version of the Microsoft Visual {cpp} Redistributable runtime libraries installed.
If you do not have these libraries installed, download them from https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist[Microsoft Visual {cpp} Redistributable latest supported downloads].


[#version-compatibility]
== Version Compatibility

The versions of the utilities installed by the tools package are the same as the corresponding Couchbase Server installation package.

For Server developer tools package, the {tools-ver} version of `cbimport`, `cbexport`, `cbbackupmgr`, and `cbq` utilities are compatible with the following Couchbase Server versions:

* 7.6.0, 7.6.1, 7.6.2, 7.6.3
* 7.2.x
* 7.1.x
* 7.0.x

You can download and use the latest version of the utilities (`cbimport`, `cbexport`, `cbbackupmgr`, and `cbq`) with earlier Couchbase Server versions.

For Server admin tools package, do the following:

* Use the `--version` option to get the version of the utility. However, for the `cbc` utility, use the `cbc version` option.
* `couchbase-cli` is a utility for administering the Couchbase cluster. Make sure that the versions of `couchbase-cli` and the Couchbase cluster match. 
* For all utilities, a feature that exists in a latest Server version only is not supported by an earlier version utility.
