[#section-new-feature-couchbase-cluster]
=== Couchbase Cluster

https://jira.issues.couchbase.com/browse/MB-62583[MB-62583]::
The `/prometheus_sd_config` endpoint  provides a new option “clusterLabels” which species the cluster name and cluster UUID be returned. Prometheus will use them as labels in time series data. This provides a method to guarantee uniqueness for stats with the same name gathered from multiple clusters.
+
[source, shell]
----
curl --get -u <username:password> \
    https://<ip-address-or-domain-name>:<port-number>/prometheus_sd_config
    -d disposition=[attachment|inline]
    -d network=[default|external]
    -d port=[insecure|secure]
    -d type=[json|yaml]
    -d clusterLabels=none|uuidOnly|uuidAndName
----

https://jira.issues.couchbase.com/browse/MB-61946[MB-61946]::
The `/pools/default/nodeServices` endpoint results now include the UUID and name of the cluster.
+
[source, shell]
----
 "clusterUUID": "0e23ca344ef4aafaf2b48ed90c5335ef",
  "clusterName": "CouchbaseTestLab"
----

[#section-new-feature-XDCR]
=== XDCR
https://jira.issues.couchbase.com/browse/MB-61048[MB-61048]::
Once faulty remote cluster credentials are fixed, XDCR will now be able to more quickly restart replications that depend on the repaired references.

[#section-new-feature-query-engine]
=== Query Engine

https://jira.issues.couchbase.com/browse/MB-63459[MB-63459]::
New to `8.0.0` is the ability to manipulate document extended attributes (xattrs) via a common SQL++ statement.
+
`INSERT` and `UPSERT` statement options may now include a “xattrs” object element detailing additions and changes to the xattrs (omissions do not delete xattrs).
+
The `UPDATE` statement now supports `SET` and `UNSET` of `meta().xattrs.+{attribute}+ elements.`

[#section-new-feature-vector-search]
=== Vector Search

* On x86 platforms, Vector Search now uses the processor's Advanced Vector Extensions 2 (AVX2) feature to improve performance.
Because of this change,  Couchbase Server running on x86 platforms requires a processor that supports these AVX2 instructions.
For more information, see xref:install:pre-install.adoc#vector_cpu_requirements[Vector Search CPU Requirements].

[#section-new-feature-index-service]
=== Index Service

https://jira.issues.couchbase.com/browse/MB-60953[MB-60953]::
We have improved the creation of large replicated partitioned index definitions
to create all replicas and partitions in the same iteration,
rather than doing it asynchronously in the background.
This leads to better utilization of DCP streams.

[#section-new-feature-tools]
=== Tools

https://jira.issues.couchbase.com/browse/MB-60337[MB-60337]::
Previously,
it was possible to remove backups which would cause dependent incremental backups
to become invalid if they depended on those deleted backups.
With this release, such deletes are prevented by default but can be overridden with the new `--disable-safe-remove-check` flag

https://jira.issues.couchbase.com/browse/MB-60676[MB-60676]::
When there are multiple backup service nodes in a cluster,
we now prevent more than one job for a repo from being run concurrently.
Previously this could happen, even though it always results in one of the jobs failing.

https://jira.issues.couchbase.com/browse/MB-61073[MB-61073]::
It is now possible to change the plan used by a repository.
The repository first needs to be paused, and then the plan can be changed,
and the repository resumed, where it will now execute the tasks from its new plan.

