[#new-features-764-cluster-manager]
=== Cluster Manager

* *https://jira.issues.couchbase.com/browse/MB-63871[MB-63871]:*
The `/prometheus_sd_config` endpoint  provides a new option `clusterLabels`
that specifies the cluster will return its name and  UUID.
Prometheus will use the labels in time series data.
This provides a method
to guarantee uniqueness for stats with the same name
gathered from multiple clusters.
+
[source,console]
----
curl --get -u <username:password> \
    http://<ip-address-or-domain-name>:<port-number>/prometheus_sd_config
    -d disposition=[attachment|inline]
    -d network=[default|external]
    -d port=[insecure|secure]
    -d type=[json|yaml]
    -d clusterLabels=none|uuidOnly|uuidAndName
----

[#new-features-764-xdcr]
=== XDCR


* *https://jira.issues.couchbase.com/browse/MB-62412[MB-62412]:*
 Once faulty remote cluster credentials are fixed, XDCR will now be able to more quickly restart replications that depend on the repaired references.

[#new-features-764-search-service]
=== Search Service

The Search Service now supports the cosine similarity metric for xref:vector-search:vector-search.adoc[Vector Search indexes].
For more information about Vector Search similarity metrics, see xref:search:child-field-options-reference.adoc[Child Field Options].
