[#new-features-764-cluster-manager]
=== Cluster Manager

* *https://jira.issues.couchbase.com/browse/MB-63871[MB-63871]:*
The `/prometheus_sd_config` endpoint  provides a new option `clusterLabels`
that specifies the cluster will return its name and  UUID.
Prometheus will use the labels in time series data.
This provides a method
to guarantee uniqueness for stats with the same name
gathered from multiple clusters.
+
[source,console]
----
curl --get -u <username:password> \
    http://<ip-address-or-domain-name>:<port-number>/prometheus_sd_config
    -d disposition=[attachment|inline]
    -d network=[default|external]
    -d port=[insecure|secure]
    -d type=[json|yaml]
    -d clusterLabels=none|uuidOnly|uuidAndName
----

[#new-features-764-xdcr]
=== XDCR


* *https://jira.issues.couchbase.com/browse/MB-62412[MB-62412]:*
 Once faulty remote cluster credentials are fixed, XDCR will now be able to more quickly restart replications that depend on the repaired references.

[#new-features-764-search-service]
=== Search Service

* The Search Service now supports the cosine similarity metric for xref:vector-search:vector-search.adoc[Vector Search indexes].
For more information about Vector Search similarity metrics, see xref:search:child-field-options-reference.adoc[Child Field Options].

* The Search Service has added a new object to JSON Search queries. 
Use this new object to view detailed query debugging information and resolve query errors in the Web Console or through the REST API.
For more information about how to run a query with this new object, see xref:search:search-request-params.adoc#validate[the validate property], xref:search:simple-search-rest-api.adoc#example-validate-a-search-query[Run a Simple Search with the REST API and curl/HTTP] or xref:search:simple-search-ui.adoc#example-validate-a-search-query[Run A Simple Search with the Web Console].

=== Supported Platforms

* Support for Windows 10 is deprecated in Couchbase Server 7.6.4.
A future release of Couchbase Server will remove support for it.

[#new-features-764-tools]
=== Tools

* *https://jira.issues.couchbase.com/browse/MB-63171[MB-63171]:*
Starting from version 7.6.4, the Couchbase Server tools packages are categorized into the Server developer tools package and the Server admin tools package.
+
The Server developer tools package is the same as the previously named Server tools package, which includes `cbimport`, `cbexport`, `cbq`, and `cbbackupmgr`.
+
The Server admin tools package is created for the Server admin users who want to download the necessary utilities to remotely administer and monitor multiple Couchbase clusters. The Server admin tools package includes the utilities `cbbackupmgr`, `cbc`, `cbdatarecovery`, `cbexport`, `cbimport`, `cbq`, `cbstats`, `couchbase-cli`, `mcstat`, `mctestauth`, and `mctimings`.
+
For details, see xref:cli:cli-intro.adoc#server-tools-packages[CLI Reference].
