= Supported Platforms
:description: Couchbase Server supports several popular operating systems and virtual environments. The Couchbase Server Web Console supports most recent major browsers.
:page-aliases: install:install-browsers

[abstract]
{description}

[#oses]
== Supported Operating Systems

Choose an operating system from the following list for your Couchbase Server deployment.

NOTE: Couchbase clusters on mixed platforms are not supported.
Nodes in a Couchbase cluster should all be running on the same OS.
Be sure to apply the same OS updates to all nodes the cluster.

ARM64 support requires ARMv8 CPUs, such as the Amazon Graviton series.

.Supported Operating Systems for Development, Testing, and Production
[cols="100,135",options="header"]
|===
| Operating System | Supported Versions (64-bit)

| Alma Linux
a|* 9.x
| Amazon Linux 2
a|* LTS (x86-64, ARM64) (deprecated in Couchbase Server 7.6)

| Amazon Linux 2023
a|* AL2023 (x86-64, ARM64)

| Debian
a| * 12.x
* 11.x

| Oracle Linux{empty}footnote:[Only the Red Hat Compatible Kernel (RHCK) is supported.
The Unbreakable Enterprise Kernel (UEK) is not supported.]
a|* 9.x
* 8.x

| Red Hat Enterprise Linux (RHEL)
a|* 9.x
* 8.x

| Rocky Linux
a|* 9.x

| SUSE Linux Enterprise Server (SLES)
a|* 15.x 
* 12.x

NOTE: Versions earlier than 12 SP2 are no longer supported in Couchbase Server 7.2 and later.

| Ubuntu
a|* 24.04 LTS (x86, ARM64)
* 22.x LTS (x86, ARM64)
* 20.04 LTS (x86, ARM64) (deprecated in Couchbase Server 7.6)

| Windows Server
a|* 2022
* 2019 (deprecated in Couchbase Server 7.6)

|===

.Supported Operating Systems for Development and Testing Only
[cols="100,135",options="header"]
|===
| Operating System | Supported Versions (64-bit)

| macOS
a|* 14 "Sonoma"
* 13 "Ventura"
* 12 "Monterey" (x86-64 and Apple Silicon ARM64) (deprecated in Couchbase Server 7.6)

| Windows Desktop
a|* 11
* 10 (requires Anniversary Update)
|===

== Supported Virtualization and Container Platforms

When running Couchbase Server in virtualized or containerized environments, base the container or VM on one of the operating systems listed under  <<Supported Operating Systems>>.
Couchbase Server has no operating system requirements for the system hosting the VM or container.

.Supported VM and Container Platforms
[cols="100,135",options="header"]
|===
| Platform | Notes

| Docker
| Couchbase Server is compatible with Docker.

You can find official Docker images at https://hub.docker.com/_/couchbase[Docker Hub].
Follow the best practices to run xref:best-practices-vm.adoc[Couchbase Server on a virtualized environment].

| Kernel-based Virtual Machine (KVM)
| Couchbase Server is compatible with KVM.

Follow the best practices to run xref:best-practices-vm.adoc[Couchbase Server on a virtualized environment].

| Kubernetes
| xref:operator::overview.adoc[Couchbase Autonomous Operator] provides Kubernetes integration.

| Red Hat OpenShift
| xref:operator::overview.adoc[Couchbase Autonomous Operator] provides Red Hat OpenShift integration.

| VMware
| Couchbase Server is compatible with VMware.

Follow the best practices to run xref:best-practices-vm.adoc[Couchbase Server on a virtualized environment].
|===

[#supported-browsers]
== Supported Web Browsers

Couchbase Web Console is supported on a variety of modern Web browsers.

.Couchbase Web Console Supported Web Browsers
|===
| Browser | Operating System (64-bit) | Browser Version | Couchbase platform

| Apple Safari
| macOS
| 11.1+
| 7.6 +
7.2 +
7.1 +
7.0

| Google Chrome
| macOS, Windows
| 67+
| 7.6 +
7.2 +
7.1 +
7.0 +

| Microsoft Edge
| Windows
| 80+
| 7.6 +
7.2 +
7.1 +
7.0 +

| Mozilla Firefox
| macOS, Windows
| 67+
| 7.6 +
7.2 +
7.1 +
7.0 +
|===

== Capella Browser Support

See xref:cloud:reference:browser-compatibility.adoc[Supported Web Browsers] for a list of the web browsers that Capella supports.
